### ISSUE TITLE
StackOverflowError when password is incorrect

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/hub-gradle-plugin#27]
Using version 3.4.1 of the hub gradle plugin I get StackOverflowErrors during execution one one project consistently. I'm not able at this point to determine what is special about this project.

The stack trace looks like this. Based on the stacktrace it looks like it's about to work because the connect socket call is being called but it's only after a very large loop within your RestConnection.java and CredentialsRestConnection.java

*Note that I cut off the stack trace because it's just repeating the last liens over and over again.
```
[07:55:37]	[Step 1/1] 07:55:35.634 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.StackOverflowError
[07:55:37]	[Step 1/1] 07:55:35.635 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:187)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
[07:55:37]	[Step 1/1] 07:55:35.636 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[07:55:37]	[Step 1/1] 07:55:35.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[07:55:37]	[Step 1/1] 07:55:35.637 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[07:55:37]	[Step 1/1] 07:55:35.638 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
[07:55:37]	[Step 1/1] 07:55:35.638 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[07:55:37]	[Step 1/1] 07:55:35.638 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[07:55:37]	[Step 1/1] 07:55:35.638 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[07:55:37]	[Step 1/1] 07:55:35.638 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[07:55:37]	[Step 1/1] 07:55:35.638 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
[07:55:37]	[Step 1/1] 07:55:35.653 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[07:55:37]	[Step 1/1] 07:55:35.653 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[07:55:37]	[Step 1/1] 07:55:35.653 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
[07:55:37]	[Step 1/1] 07:55:35.653 [ERROR] [org.gradle.BuildExceptionReporter] 	at okhttp3.RealCall.execute(RealCall.java:60)
[07:55:37]	[Step 1/1] 07:55:35.653 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:258)
[07:55:37]	[Step 1/1] 07:55:35.654 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:252)
[07:55:37]	[Step 1/1] 07:55:35.654 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.CredentialsRestConnection.clientAuthenticate(CredentialsRestConnection.java:104)
[07:55:37]	[Step 1/1] 07:55:35.654 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.connect(RestConnection.java:130)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:261)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:252)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.CredentialsRestConnection.clientAuthenticate(CredentialsRestConnection.java:104)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.connect(RestConnection.java:130)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:261)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:252)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.CredentialsRestConnection.clientAuthenticate(CredentialsRestConnection.java:104)
[07:55:37]	[Step 1/1] 07:55:35.655 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.blackducksoftware.integration.hub.rest.RestConnection.connect(RestConnection.java:130)
```

**Comment by imbeyondboredom** [comment]
I figured it out but this should still be fixed. This happens when the password is incorrect.

**Comment by ekerwin** [comment]
Yes - this was an issue in the underlying library the hub-gradle plugin uses. We addressed it there, so the next release of the hub-gradle plugin will have this taken care of. I'll close this when we release.
